# controllers prefix, on prod it sets via WAR file name.
server:
  servlet:
    context-path: /scp-reader/api

hibernate:
  show_sql: false

spring:
  datasource:
    hikari:
      auto-commit: true
      connection-timeout: 20000
      idle-timeout: 10000
      max-lifetime: 1000
      maximum-pool-size: 20
      minimum-idle: 10
    password: PASTE_PASSWORD_HERE
    platform: postgres
    url: jdbc:postgresql://localhost:5432/${my.db.name}
    username: postgres
  flyway:
    baseline-on-migrate: true
    locations: classpath:migration
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
  jackson:
    serialization:
      indent_output: true
  jmx:
    default-domain: ${my.db.name}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        connection:
          charSet: UTF-8
        temp:
          use_jdbc_metadata_defaults: false
  main:
    banner-mode: 'off'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  file: logs/myLog.log
  file.max-history: 15
  level:
    org:
      flywaydb: INFO
      hibernate: ERROR
      hibernate.SQL: ERROR
      hibernate.type: ERROR
      springframework: ERROR
      springframework.web: ERROR
    root: ERROR
  pattern:
    console: '%d{HH:mm:ss.SSS} %msg%n'

my:
  api:
    facebook:
      client_id: CLIENT_ID_HERE
      client_secret: CLIENT_SECRET_HERE
    google:
      client_id: CLIENT_ID_HERE
      client_secret: CLIENT_SECRET_HERE
  db:
    name: scp_reader
