# controllers prefix, on prod it sets via WAR file name.
server:
  servlet:
    context-path: /scp-reader/api
  error:
    include-message: always
    include-binding-errors: always

hibernate:
  show_sql: false

spring:
  mail:
    default-encoding: UTF-8
    host: mail.${my.site.domain}
    port: 587
    username: no-reply@${my.site.domain}
    password: "PASSWORD_HERE"
    properties.mail:
      user: no-reply@${my.site.domain}
      from: no-reply@${my.site.domain}
      smtp:
        #need this for EHLO check
        localhost: ${my.site.domain}
        auth: true
        starttls.enable: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  mvc:
    static-path-pattern: /resources/static/**
  datasource:
    hikari:
      auto-commit: true
      connection-timeout: 20000
      idle-timeout: 10000
      max-lifetime: 1000
      maximum-pool-size: 20
      minimum-idle: 10
    password: PASTE_PASSWORD_HERE
    platform: postgres
    url: jdbc:postgresql://localhost:5432/${my.db.name}
    username: postgres
  flyway:
    baseline-on-migrate: true
    locations: classpath:migration
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
  jackson:
    serialization:
      indent_output: true
  jmx:
    default-domain: ${my.db.name}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        connection:
          charSet: UTF-8
        temp:
          use_jdbc_metadata_defaults: false
  main:
    banner-mode: 'off'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  file:
    name: logs/myLog.log
    max-history: 15
  level:
    org:
      flywaydb: INFO
      hibernate: ERROR
      hibernate.SQL: ERROR
      hibernate.type: ERROR
      springframework: ERROR
      springframework.web: ERROR
      apache.catalina.session.ManagerBase: ERROR
    com:
      zaxxer:
        hikari: ERROR
        hikari.HikariConfig: ERROR
        hikari.pool:
          HikariPool: ERROR
          PoolBase: ERROR
    root: ERROR
  pattern:
    console: '%d{HH:mm:ss.SSS} %msg%n'

my:
  api:
    huawei:
      client_id: CLIENT_ID_HERE
      client_secret: CLIENT_SECRET_HERE
    facebook:
      client_id: CLIENT_ID_HERE
      client_secret: CLIENT_SECRET_HERE
    google:
      client_id: CLIENT_ID_HERE
      client_secret: CLIENT_SECRET_HERE
  db:
    name: scp_reader
  #site
  site:
    domain: scp-reader.com
  #mail:
  mail:
    admin:
      address: admin@${my.site.domain}
