package ru.kuchanov.scpreaderapi.model.huawei.purchase

data class InAppPurchaseData(
        val applicationId: Long,
        val autoRenewing: Boolean,
        val orderId: String,
        val kind: Int,
        val packageName: String?,
        val productId: String,
        val productName: String?,
        val purchaseState: Int,
        val developerPayload: String?,
        val developerChallenge: String?,
        val consumptionState: Int?,
        val purchaseToken: String,
        val purchaseType: Int?,
        val currency: String?,
        val price: Long?,
        val country: String?,
        val payType: String?,
        val payOrderId: String?,
        val accountFlag: Int?,
        //The following parameters are returned only in the subscription scenario.
        /**
         * Mandatory for subs
         */
        val lastOrderId: String?,
        val productGroup: String?,
        val purchaseTime: Long?,
        val oriPurchaseTime: Long?,
        val subscriptionId: String?,
        val oriSubscriptionId: String?,
        val quantity: Int?,
        val daysLasted: Long?,
        val numOfPeriods: Long?,
        val numOfDiscount: Long?,
        val expirationDate: Long?,
        val expirationIntent: Int?,
        val retryFlag: Int?,
        val introductoryFlag: Int?,
        val trialFlag: Int?,
        val cancelTime: Long?,
        val cancelReason: Int?,
        val appInfo: String?,
        val notifyClosed: Int?,
        val renewStatus: Int?,
        val priceConsentStatus: Int?,
        val renewPrice: Long?,
        val subIsvalid: Boolean?,
        val deferFlag: Int?,
        val cancelWay: Int?,
        val cancellationTime: Long?,
        val cancelledSubKeepDays: Int?,
        val confirmed: Int?,
        val resumeTime: Long?,
        val surveyReason: Int?,
        val surveyDetails: String?
)